### ISSUE TITLE
Owner permission on read isn't excluding other users

### ISSUE THREAD

**Issue by redBaronNc** [tjwebb/sails-permissions#123] opened 2015-08-20 09:05 UTC
Hello
I am trying to understand how a permission with relation set to owner works.
I have 2 users. One of the has the standard "<b>registered</b>" role. The permissions are as I can see:

 	Model 	Action 	Relation
 	Permission 	read 	role
 	Model 	read 	role
 	User 	update 	owner 
 	User 	read 	owner

As I understand, that means my "<b>registered</b>"  user should be able to update and read his own user instance.

My issue is that this user can also <b>read other user instances</b>! Is this normal? If so it does not seem logical, and I probably need some help understanding how you use the ownership.

**Comment by jacobfunch** [comment] 2015-08-21 06:36
I can confirm this. I did a bit more testing and it seems that UPDATE works as expected.

**Action "update"**

Model | Action | Relation | Role
------------ | ------------- | ------------- | -------------
3 | update | role | admin
3 | update | owner | registered

As expected: When user is registered he is not allowed to update foreign rows, but his own.

**Action "read"**

Model | Action | Relation | Role
------------ | ------------- | ------------- | -------------
3 | read | role | admin
3 | read | owner | registered

Expected: Registered can only read his own.
Result: Registered can read all the rows.

Maybe I just misunderstood the concept of ownership?

**Comment by ryanwilliamquinn** [comment] 2015-08-23 21:45
Hmm, if that is true, it is not functioning as expected.  Ownership relation should only give you access to objects that you own.  I will take a look and get back to you.

**Comment by ryanwilliamquinn** [comment] 2015-08-27 01:15
Are you sure there aren't any other existing permissions?  I took a quick look at this, and it is working as expected.  Non-admin users only see themselves.  Here are the related permissions:

```
sails console
sails> Model.find({identity: 'user'}, console.log)
sails> null [ { name: 'User',
    identity: 'user',
    attributes:
     { username: { type: 'string', unique: true, index: true, notNull: true },
       email: { type: 'email', notNull: true, unique: true, index: true },
       passports: { collection: 'passport', via: 'user' },
       roles: { collection: 'role', via: 'users', dominant: true },
       permissions: { collection: 'permission', via: 'user' },
       createdBy: { model: 'user', index: true },
       owner: { model: 'user', index: true },
       id:
        { type: 'integer',
          autoIncrement: true,
          primaryKey: true,
          unique: true },
       createdAt: { type: 'datetime', default: 'NOW' },
       updatedAt: { type: 'datetime', default: 'NOW' } },
    id: 25 } ]
sails> Permission.find({model: 25, action: 'read'}).populate('role').exec(console.log)
undefined
sails> null [ { model: 25,
    role:
     { name: 'admin',
       active: true,
       createdAt: '2015-08-27T01:09:02.001Z',
       updatedAt: '2015-08-27T01:09:02.001Z',
       id: 17 },
    action: 'read',
    relation: 'role',
    createdAt: '2015-08-27T01:09:02.234Z',
    updatedAt: '2015-08-27T01:09:02.234Z',
    id: 134 },
  { model: 25,
    role:
     { name: 'registered',
       active: true,
       createdAt: '2015-08-27T01:09:02.003Z',
       updatedAt: '2015-08-27T01:09:02.003Z',
       id: 18 },
    action: 'read',
    relation: 'owner',
    createdAt: '2015-08-27T01:09:02.245Z',
    updatedAt: '2015-08-27T01:09:02.245Z',
    id: 140 } ]
```

**Comment by redBaronNc** [comment] 2015-08-27 08:27
Hello, I checked again.
My user has the registered role only.
the registered role only has 2 permissions on the user model (id:4):
[
  {
    "model": 4,
    "role": 2,
    "action": "update",
    "relation": "owner",
    "id": 19,
    "createdAt": "2015-07-09T10:09:24.452Z",
    "updatedAt": "2015-07-09T10:09:24.452Z"
  },
  {
    "model": 4,
    "role": 2,
    "action": "read",
    "relation": "owner",
    "id": 20,
    "createdAt": "2015-07-09T10:09:24.458Z",
    "updatedAt": "2015-07-09T10:09:24.458Z"
  }
]

I am not able to retrieve the list of all users (as expected /user returns forbidden). But I can read each user record individually while connected as this registered user.
I am using sails-permission 1.4.1

**Comment by ryanwilliamquinn** [comment] 2015-08-28 00:57
Thanks for uncovering this, it was related to an issue with how waterline treats 'findOne' blueprint routes.

**Comment by wadeos** [comment] 2015-08-29 04:44
I also have this issue, registered users can only find themselves using findWhere. but if you pass a user id on the findOne it will return any user.

**Comment by dottodot** [comment] 2015-10-10 09:42
Looks like this is fixed in v1.4.5 `User.find` only returns the one user for the registered role

**Closed** 2015-10-11 14:14 UTC

**Comment by asmello** [comment] 2016-04-17 15:16
I'm experiencing the same issue with v2.2.0.

I checked, and there are only three `read` permissions granted for my test user:

| Model  | Action | Relation | Role | Criteria
| --------- | -------- | ----------- | ------ | --------- |
| 10  |  read  | role | public | `{ isPublic: true, blacklist: [ 'isBirthdayPublic' ] }` |
| 10  | read | role | public | `{ isPublic: false, blacklist: [ 'isBirthdayPublic', 'birthday' ] }` |
| 10  | read | owner | registered | None |

However, when I send a GET request to `/profile` the silly log says:
```
PermissionPolicy: 3 permissions grant GET on Profile for test@test.com
```
And I get no filtering at all...

**Comment by asmello** [comment] 2016-04-18 12:50
I've identified the issue.

In `RolePolicy.js:25`

```javascript
// continue if there exist role Permissions which grant the asserted privilege
  if (!_lodash2['default'].isEmpty(relations.role)) {
    return next();
  }
```

This forwards the permissions without checking the owner relation. My user has both owner and role permissions, but only the role permissions set criteria. `CriteriaPolicy.js:43`

```javascript
var criteria = _lodash2['default'].compact(_lodash2['default'].flatten(_lodash2['default'].map(_lodash2['default'].pluck(permissions, 'criteria'), function (c) {
      if (c.length == 0) {
        return [{ where: {} }];
      }
      return c;
    })));
```

does not check the relation attribute, so the `where` clause of the owner permission is included, even though it was never checked. The fix is to check if owner and filter out owner permissions before using the list of criteria.
